const JOBS_DATA = [
    {
        id: 1,
        title: "SDE Intern",
        company: "Amazon",
        location: "Bangalore",
        mode: "Onsite",
        experience: "Fresher",
        skills: ["Java", "DSA", "AWS"],
        source: "LinkedIn",
        postedDaysAgo: 2,
        salaryRange: "₹40k–₹80k/month",
        applyUrl: "https://amazon.jobs",
        description: "Join our core engineering team to build scalable systems. Requires strong DSA/Java skills. Great opportunity for pre-final year students."
    },
    {
        id: 2,
        title: "Frontend Developer (React)",
        company: "Swiggy",
        location: "Remote",
        mode: "Remote",
        experience: "1-3",
        skills: ["React", "Redux", "CSS"],
        source: "Naukri",
        postedDaysAgo: 0,
        salaryRange: "12–18 LPA",
        applyUrl: "https://careers.swiggy.com",
        description: "Looking for a UI engineer to work on our consumer facing app. Experience with React and performance optimization is a must."
    },
    {
        id: 3,
        title: "Graduate Engineer Trainee",
        company: "TCS",
        location: "Pune",
        mode: "Onsite",
        experience: "Fresher",
        skills: ["Python", "SQL", "Basics"],
        source: "TCS Careers",
        postedDaysAgo: 5,
        salaryRange: "3–4.5 LPA",
        applyUrl: "https://tcs.com/careers",
        description: "Mass hiring drive for 2024/2025 graduates. Training provided in Java/Python. Aptitude test mandatory."
    },
    {
        id: 4,
        title: "Backend Engineer",
        company: "Razorpay",
        location: "Bangalore",
        mode: "Hybrid",
        experience: "1-3",
        skills: ["Go", "PHP", "PostgreSQL"],
        source: "LinkedIn",
        postedDaysAgo: 1,
        salaryRange: "18–24 LPA",
        applyUrl: "https://razorpay.com/jobs",
        description: "Scale high-throughput payment systems. Work with Go and distributed architectures. Competitive compensation."
    },
    {
        id: 5,
        title: "Data Analyst Intern",
        company: "Flipkart",
        location: "Bangalore",
        mode: "Hybrid",
        experience: "Fresher",
        skills: ["SQL", "Excel", "Python"],
        source: "Indeed",
        postedDaysAgo: 3,
        salaryRange: "₹30k/month",
        applyUrl: "https://flipkartcareers.com",
        description: "Analyze user behavior data to drive business decisions. Strong SQL and visualization skills required."
    },
    {
        id: 6,
        title: "Java Developer",
        company: "Infosys",
        location: "Mysore",
        mode: "Onsite",
        experience: "0-1",
        skills: ["Java", "Spring Boot", "MySQL"],
        source: "Naukri",
        postedDaysAgo: 6,
        salaryRange: "4–6 LPA",
        applyUrl: "https://infosys.com/careers",
        description: "Hiring for multiple projects. Knowledge of Spring Boot and Microservices is an added advantage."
    },
    {
        id: 7,
        title: "UI/UX Designer",
        company: "PhonePe",
        location: "Bangalore",
        mode: "Onsite",
        experience: "1-3",
        skills: ["Figma", "Prototyping"],
        source: "LinkedIn",
        postedDaysAgo: 2,
        salaryRange: "10–15 LPA",
        applyUrl: "https://phonepe.com/careers",
        description: "Design intuitive user journeys for millions of users. Portfolio required."
    },
    {
        id: 8,
        title: "DevOps Engineer",
        company: "Zoho",
        location: "Chennai",
        mode: "Onsite",
        experience: "3-5",
        skills: ["Linux", "Docker", "Jenkins"],
        source: "Zoho Corp",
        postedDaysAgo: 4,
        salaryRange: "8–12 LPA",
        applyUrl: "https://zoho.com/careers",
        description: "Manage CI/CD pipelines and server infrastructure. Deep understanding of Linux required."
    },
    {
        id: 9,
        title: "Associate Software Engineer",
        company: "Accenture",
        location: "Hyderabad",
        mode: "Hybrid",
        experience: "0-1",
        skills: ["Java", ".NET", "Testing"],
        source: "Naukri",
        postedDaysAgo: 7,
        salaryRange: "4.5–6.5 LPA",
        applyUrl: "https://accenture.com",
        description: "Entry level software engineering role. Training provided across various technology stacks."
    },
    {
        id: 10,
        title: "Product Intern",
        company: "CRED",
        location: "Bangalore",
        mode: "Onsite",
        experience: "Fresher",
        skills: ["Product Sense", "Analytics"],
        source: "LinkedIn",
        postedDaysAgo: 1,
        salaryRange: "₹50k/month",
        applyUrl: "https://cred.club",
        description: "Work directly with founders to shape product features for high-trust members."
    },
    {
        id: 11,
        title: "Python Developer",
        company: "Wipro",
        location: "Hyderabad",
        mode: "Onsite",
        experience: "1-3",
        skills: ["Django", "Python", "API"],
        source: "Indeed",
        postedDaysAgo: 8,
        salaryRange: "5–8 LPA",
        applyUrl: "https://wipro.com",
        description: "Backend development for varied clients. Experience with Django/Flask preferred."
    },
    {
        id: 12,
        title: "Android Developer",
        company: "Paytm",
        location: "Noida",
        mode: "Hybrid",
        experience: "1-3",
        skills: ["Kotlin", "Android SDK"],
        source: "Naukri",
        postedDaysAgo: 3,
        salaryRange: "10–16 LPA",
        applyUrl: "https://paytm.com/careers",
        description: "Build payment features for the Paytm app. Strong Kotlin knowledge required."
    },
    {
        id: 13,
        title: "QA Engineer",
        company: "Capgemini",
        location: "Mumbai",
        mode: "Onsite",
        experience: "0-1",
        skills: ["Selenium", "Java", "Manual Testing"],
        source: "LinkedIn",
        postedDaysAgo: 5,
        salaryRange: "4–5.5 LPA",
        applyUrl: "https://capgemini.com",
        description: "Automation and manual testing for banking clients. Selenium knowledge is key."
    },
    {
        id: 14,
        title: "Full Stack Intern",
        company: "Juspay",
        location: "Bangalore",
        mode: "Onsite",
        experience: "Fresher",
        skills: ["Haskell", "PureScript", "React"],
        source: "Juspay Careers",
        postedDaysAgo: 0,
        salaryRange: "₹30k–₹40k/month",
        applyUrl: "https://juspay.in",
        description: "Unique opportunity to work with functional programming (Haskell/PureScript). Steep learning curve."
    },
    {
        id: 15,
        title: "Cloud Support Associate",
        company: "Oracle",
        location: "Bangalore",
        mode: "Hybrid",
        experience: "0-1",
        skills: ["Cloud", "Networking", "Linux"],
        source: "Indeed",
        postedDaysAgo: 2,
        salaryRange: "6–9 LPA",
        applyUrl: "https://oracle.com/careers",
        description: "Support Oracle Cloud Infrastructure customers. Networking certification (CCNA/related) preferred."
    },
    {
        id: 16,
        title: "React Native Developer",
        company: "Zomato",
        location: "Gurgaon",
        mode: "Onsite",
        experience: "1-3",
        skills: ["React Native", "Redux", "Mobile"],
        source: "LinkedIn",
        postedDaysAgo: 1,
        salaryRange: "15–22 LPA",
        applyUrl: "https://zomato.com/careers",
        description: "Build cross-platform mobile experiences for food delivery."
    },
    {
        id: 17,
        title: "System Engineer",
        company: "IBM",
        location: "Pune",
        mode: "Hybrid",
        experience: "0-1",
        skills: ["Unix", "Shell Scripting", "C++"],
        source: "Naukri",
        postedDaysAgo: 4,
        salaryRange: "5–7 LPA",
        applyUrl: "https://ibm.com/careers",
        description: "Infrastructure monitoring and system maintenance. Good command over Unix systems."
    },
    {
        id: 18,
        title: "Business Analyst",
        company: "Deloitte",
        location: "Hyderabad",
        mode: "Onsite",
        experience: "0-1",
        skills: ["Analysis", "Documentation", "Agile"],
        source: "LinkedIn",
        postedDaysAgo: 2,
        salaryRange: "6–8 LPA",
        applyUrl: "https://deloitte.com",
        description: "Bridge the gap between IT and business. Gather requirements and document user stories."
    },
    {
        id: 19,
        title: "Golang Developer",
        company: "Zerodha",
        location: "Bangalore",
        mode: "Onsite",
        experience: "1-3",
        skills: ["Go", "Distributed Systems"],
        source: "Zerodha Specs",
        postedDaysAgo: 9,
        salaryRange: "12–18 LPA",
        applyUrl: "https://zerodha.com/careers",
        description: "Work on high-performance trading systems. Heavy focus on concurrency and optimization."
    },
    {
        id: 20,
        title: "Cyber Security Analyst",
        company: "PwC",
        location: "Bangalore",
        mode: "Hybrid",
        experience: "1-3",
        skills: ["Security", "Network", "VAPT"],
        source: "Naukri",
        postedDaysAgo: 3,
        salaryRange: "8–12 LPA",
        applyUrl: "https://pwc.com",
        description: "Monitor and analyze security threats. Conduct vulnerability assessments."
    },
    {
        id: 21,
        title: "Data Engineer",
        company: "Fractal",
        location: "Mumbai",
        mode: "Hybrid",
        experience: "3-5",
        skills: ["Spark", "Hadoop", "Python"],
        source: "LinkedIn",
        postedDaysAgo: 5,
        salaryRange: "14–20 LPA",
        applyUrl: "https://fractal.ai",
        description: "Build scalable data pipelines. Experience with big data technologies is mandatory."
    },
    {
        id: 22,
        title: "Technical Writer",
        company: "Freshworks",
        location: "Chennai",
        mode: "Onsite",
        experience: "1-3",
        skills: ["Writing", "API Documentation"],
        source: "Freshworks Careers",
        postedDaysAgo: 6,
        salaryRange: "6–9 LPA",
        applyUrl: "https://freshworks.com",
        description: "Create clear and concise API documentation for developers."
    },
    {
        id: 23,
        title: "Frontend Intern",
        company: "Groww",
        location: "Bangalore",
        mode: "Onsite",
        experience: "Fresher",
        skills: ["React", "HTML/CSS"],
        source: "LinkedIn",
        postedDaysAgo: 1,
        salaryRange: "₹25k/month",
        applyUrl: "https://groww.in/careers",
        description: "Learn and build investment dashboards. Mentorship from senior devs."
    },
    {
        id: 24,
        title: "Support Engineer",
        company: "Microsoft",
        location: "Bangalore",
        mode: "Remote",
        experience: "0-1",
        skills: ["Azure", "Windows Server", "Troubleshooting"],
        source: "Microsoft Careers",
        postedDaysAgo: 2,
        salaryRange: "9–12 LPA",
        applyUrl: "https://careers.microsoft.com",
        description: "Provide technical support for enterprise customers using Azure services."
    },
    {
        id: 25,
        title: "PHP Developer",
        company: "Magneto It Solutions",
        location: "Ahmedabad",
        mode: "Onsite",
        experience: "1-3",
        skills: ["PHP", "Laravel", "MySQL"],
        source: "Indeed",
        postedDaysAgo: 7,
        salaryRange: "4–6 LPA",
        applyUrl: "https://magnetoitsolutions.com",
        description: "E-commerce development using Magento/Laravel frameworks."
    },
    {
        id: 26,
        title: "Machine Learning Intern",
        company: "InMobi",
        location: "Bangalore",
        mode: "Hybrid",
        experience: "Fresher",
        skills: ["Python", "TensorFlow", "ML"],
        source: "LinkedIn",
        postedDaysAgo: 3,
        salaryRange: "₹45k/month",
        applyUrl: "https://inmobi.com",
        description: "Work on ad-recommendation algorithms given large datasets."
    },
    {
        id: 27,
        title: "Node.js Developer",
        company: "Dream11",
        location: "Mumbai",
        mode: "Onsite",
        experience: "1-3",
        skills: ["Node.js", "Redis", "Socket.io"],
        source: "LinkedIn",
        postedDaysAgo: 0,
        salaryRange: "15–25 LPA",
        applyUrl: "https://dream11.com",
        description: "Handle massive scale real-time traffic during matches. Node.js mastery required."
    },
    {
        id: 28,
        title: "Angular Developer",
        company: "Mindtree",
        location: "Bhubaneswar",
        mode: "Onsite",
        experience: "3-5",
        skills: ["Angular", "TypeScript"],
        source: "Naukri",
        postedDaysAgo: 5,
        salaryRange: "8–13 LPA",
        applyUrl: "https://mindtree.com",
        description: "Enterprise application development using Angular framework."
    },
    {
        id: 29,
        title: "Salesforce Developer",
        company: "Tech Mahindra",
        location: "Pune",
        mode: "Hybrid",
        experience: "1-3",
        skills: ["Apex", "Visualforce", "Salesforce"],
        source: "Naukri",
        postedDaysAgo: 4,
        salaryRange: "6–9 LPA",
        applyUrl: "https://techmahindra.com",
        description: "Customize Salesforce CRM for international clients. Certification preferred."
    },
    {
        id: 30,
        title: "Game Developer",
        company: "Moonfrog",
        location: "Bangalore",
        mode: "Onsite",
        experience: "1-3",
        skills: ["Unity", "C#"],
        source: "LinkedIn",
        postedDaysAgo: 8,
        salaryRange: "10–16 LPA",
        applyUrl: "https://moonfroglabs.com",
        description: "Develop mobile card games played by millions. Unity 3D experience needed."
    },
    {
        id: 31,
        title: "SDE-1",
        company: "Meesho",
        location: "Bangalore",
        mode: "Remote",
        experience: "0-1",
        skills: ["Java", "Spring", "Kafka"],
        source: "Meesho Careers",
        postedDaysAgo: 1,
        salaryRange: "16–22 LPA",
        applyUrl: "https://meesho.com/careers",
        description: "Backend role for e-commerce supply chain. High ownership culture."
    },
    {
        id: 32,
        title: "Flutter Developer",
        company: "Urban Company",
        location: "Gurgaon",
        mode: "Hybrid",
        experience: "1-3",
        skills: ["Flutter", "Dart"],
        source: "LinkedIn",
        postedDaysAgo: 2,
        salaryRange: "12–18 LPA",
        applyUrl: "https://urbancompany.com",
        description: "Build partner and customer apps using Flutter."
    },
    {
        id: 33,
        title: "Research Intern",
        company: "Google Research India",
        location: "Bangalore",
        mode: "Onsite",
        experience: "Fresher",
        skills: ["AI/ML", "Research"],
        source: "Google Careers",
        postedDaysAgo: 9,
        salaryRange: "₹80k/month",
        applyUrl: "https://careers.google.com",
        description: "Work on cutting edge AI research problems. PhD/Masters preferred but talented undergrads welcome."
    },
    {
        id: 34,
        title: "HR Intern",
        company: "Ola",
        location: "Bangalore",
        mode: "Onsite",
        experience: "Fresher",
        skills: ["Communication", "Excel"],
        source: "LinkedIn",
        postedDaysAgo: 6,
        salaryRange: "₹15k/month",
        applyUrl: "https://olacabs.com",
        description: "Assist with recruitment drives and employee onboarding."
    },
    {
        id: 35,
        title: "Network Engineer",
        company: "Cisco",
        location: "Bangalore",
        mode: "Hybrid",
        experience: "0-1",
        skills: ["Networking", "CCNA", "Python"],
        source: "Cisco Careers",
        postedDaysAgo: 3,
        salaryRange: "10–14 LPA",
        applyUrl: "https://cisco.com/careers",
        description: "Innovate in networking hardware and software. Scripting skills valued."
    },
    {
        id: 36,
        title: "Software Engineer",
        company: "HCL Tech",
        location: "Noida",
        mode: "Onsite",
        experience: "1-3",
        skills: ["C#", ".NET", "SQL"],
        source: "Naukri",
        postedDaysAgo: 5,
        salaryRange: "4.5–7 LPA",
        applyUrl: "https://hcltech.com",
        description: "Legacy system maintenance and new feature development for banking client."
    },
    {
        id: 37,
        title: "Ruby on Rails Developer",
        company: "SaaS Labs",
        location: "Noida",
        mode: "Remote",
        experience: "1-3",
        skills: ["Ruby", "Rails", "Postgres"],
        source: "LinkedIn",
        postedDaysAgo: 7,
        salaryRange: "10–15 LPA",
        applyUrl: "https://saaslabs.co",
        description: "Build communication tools for sales teams. Remote-first culture."
    },
    {
        id: 38,
        title: "Blockchain Developer",
        company: "CoinSwitch",
        location: "Bangalore",
        mode: "Hybrid",
        experience: "1-3",
        skills: ["Solidity", "Smart Contracts"],
        source: "LinkedIn",
        postedDaysAgo: 2,
        salaryRange: "18–28 LPA",
        applyUrl: "https://coinswitch.co",
        description: "Crypto exchange platform development. Deep blockchain knowledge required."
    },
    {
        id: 39,
        title: "Marketing Intern",
        company: "Boat",
        location: "Delhi",
        mode: "Onsite",
        experience: "Fresher",
        skills: ["Social Media", "SEO"],
        source: "Internshala",
        postedDaysAgo: 1,
        salaryRange: "₹10k/month",
        applyUrl: "https://boat-lifestyle.com",
        description: "Social media content creation and community management for audio brand."
    },
    {
        id: 40,
        title: "Java Developer",
        company: "Cognizant",
        location: "Kolkata",
        mode: "Hybrid",
        experience: "3-5",
        skills: ["Spring", "Hibernate", "Java"],
        source: "Naukri",
        postedDaysAgo: 4,
        salaryRange: "6–10 LPA",
        applyUrl: "https://cognizant.com",
        description: "Senior developer role for US healthcare client projects."
    },
    {
        id: 41,
        title: "Embedded Engineer",
        company: "Qualcomm",
        location: "Hyderabad",
        mode: "Onsite",
        experience: "1-3",
        skills: ["C", "RTOS", "Embedded"],
        source: "LinkedIn",
        postedDaysAgo: 5,
        salaryRange: "12–18 LPA",
        applyUrl: "https://qualcomm.com",
        description: "Firmware development for mobile chipsets. Low-level debugging required."
    },
    {
        id: 42,
        title: "Frontend Engineer",
        company: "Postman",
        location: "Bangalore",
        mode: "Hybrid",
        experience: "1-3",
        skills: ["React", "JavaScript", "Electron"],
        source: "Postman Careers",
        postedDaysAgo: 3,
        salaryRange: "15–20 LPA",
        applyUrl: "https://postman.com/careers",
        description: "Build the world's leading API collaboration platform."
    },
    {
        id: 43,
        title: "Analyst",
        company: "Goldman Sachs",
        location: "Bangalore",
        mode: "Onsite",
        experience: "0-1",
        skills: ["Java", "Slang", "Finance"],
        source: "LinkedIn",
        postedDaysAgo: 0,
        salaryRange: "20–25 LPA",
        applyUrl: "https://goldmansachs.com",
        description: "Technology analyst role in the investment banking division."
    },
    {
        id: 44,
        title: "iOS Developer",
        company: "Dunzo",
        location: "Bangalore",
        mode: "Onsite",
        experience: "1-3",
        skills: ["Swift", "iOS", "Objective-C"],
        source: "LinkedIn",
        postedDaysAgo: 6,
        salaryRange: "12–18 LPA",
        applyUrl: "https://dunzo.com",
        description: "Hyperlocal delivery app development. Swift UI experience is a plus."
    },
    {
        id: 45,
        title: "Intern - Software",
        company: "Nvidia",
        location: "Pune",
        mode: "Onsite",
        experience: "Fresher",
        skills: ["C++", "Graphics", "CUDA"],
        source: "Nvidia Careers",
        postedDaysAgo: 2,
        salaryRange: "₹45k/month",
        applyUrl: "https://nvidia.com",
        description: "GPU driver development and testing. Strong C++ concepts needed."
    },
    {
        id: 46,
        title: "Site Reliability Engineer",
        company: "Hotstar",
        location: "Mumbai",
        mode: "Remote",
        experience: "3-5",
        skills: ["Kubernetes", "AWS", "Go"],
        source: "LinkedIn",
        postedDaysAgo: 4,
        salaryRange: "20–30 LPA",
        applyUrl: "https://hotstar.com",
        description: "Manage infrastructure for millions of concurrent live streaming users."
    },
    {
        id: 47,
        title: "Software Engineer",
        company: "Adobe",
        location: "Noida",
        mode: "Hybrid",
        experience: "0-1",
        skills: ["C++", "Algorithms", "OS"],
        source: "Adobe Careers",
        postedDaysAgo: 7,
        salaryRange: "14–20 LPA",
        applyUrl: "https://adobe.com/careers",
        description: "Core desktop product development. Deep OS understanding required."
    },
    {
        id: 48,
        title: "Full Stack Developer",
        company: "Lenskart",
        location: "Delhi",
        mode: "Onsite",
        experience: "1-3",
        skills: ["MERN", "Node", "React"],
        source: "Naukri",
        postedDaysAgo: 3,
        salaryRange: "8–14 LPA",
        applyUrl: "https://lenskart.com",
        description: "omnichannel retail tech. Work on POS and user facing website."
    },
    {
        id: 49,
        title: "Testing Engineer",
        company: "LTI Mindtree",
        location: "Pune",
        mode: "Onsite",
        experience: "0-1",
        skills: ["Automation", "Java", "SQL"],
        source: "Naukri",
        postedDaysAgo: 5,
        salaryRange: "4–5 LPA",
        applyUrl: "https://ltimindtree.com",
        description: "Quality assurance for insurance projects."
    },
    {
        id: 50,
        title: "Security Engineer",
        company: "Ola Electric",
        location: "Bangalore",
        mode: "Onsite",
        experience: "1-3",
        skills: ["IoT Security", "Pen Testing"],
        source: "LinkedIn",
        postedDaysAgo: 2,
        salaryRange: "12–18 LPA",
        applyUrl: "https://olaelectric.com",
        description: "Secure connected vehicle infrastructure and charging network."
    },
    {
        id: 51,
        title: "Associate",
        company: "JP Morgan Chase",
        location: "Mumbai",
        mode: "Hybrid",
        experience: "1-3",
        skills: ["Java", "Spring", "React"],
        source: "LinkedIn",
        postedDaysAgo: 1,
        salaryRange: "16–22 LPA",
        applyUrl: "https://jpmorganchase.com",
        description: "Full stack development for internal banking tools."
    },
    {
        id: 52,
        title: "Graphic Design Intern",
        company: "Nykaa",
        location: "Mumbai",
        mode: "Onsite",
        experience: "Fresher",
        skills: ["Photoshop", "Illustrator"],
        source: "Internshala",
        postedDaysAgo: 3,
        salaryRange: "₹15k/month",
        applyUrl: "https://nykaa.com",
        description: "Create visual assets for marketing campaigns and app banners."
    },
    {
        id: 53,
        title: "React Developer",
        company: "CarDekho",
        location: "Jaipur",
        mode: "Onsite",
        experience: "1-3",
        skills: ["React", "Redux"],
        source: "Naukri",
        postedDaysAgo: 6,
        salaryRange: "6–10 LPA",
        applyUrl: "https://cardekho.com",
        description: "Frontend development for auto portal. Performance focus."
    },
    {
        id: 54,
        title: "Big Data Engineer",
        company: "Mu Sigma",
        location: "Bangalore",
        mode: "Onsite",
        experience: "0-1",
        skills: ["SQL", "Statistics", "Python"],
        source: "Campus",
        postedDaysAgo: 8,
        salaryRange: "5–7 LPA",
        applyUrl: "https://mu-sigma.com",
        description: "Decision sciences and analytics role. Intensive training program."
    },
    {
        id: 55,
        title: "Product Manager",
        company: "Udaan",
        location: "Bangalore",
        mode: "Onsite",
        experience: "3-5",
        skills: ["Product", "B2B", "Strategy"],
        source: "LinkedIn",
        postedDaysAgo: 4,
        salaryRange: "25–35 LPA",
        applyUrl: "https://udaan.com",
        description: "Lead product vertical for B2B e-commerce platform. High impact role."
    },
    {
        id: 56,
        title: "Support Specialist",
        company: "Dell",
        location: "Bangalore",
        mode: "Remote",
        experience: "0-1",
        skills: ["Hardware", "Windows", "Communication"],
        source: "Indeed",
        postedDaysAgo: 2,
        salaryRange: "4–6 LPA",
        applyUrl: "https://dell.com",
        description: "Remote technical support for North American customers."
    },
    {
        id: 57,
        title: "RPA Developer",
        company: "UiPath",
        location: "Bangalore",
        mode: "Hybrid",
        experience: "1-3",
        skills: ["UiPath", ".NET"],
        source: "LinkedIn",
        postedDaysAgo: 5,
        salaryRange: "10–15 LPA",
        applyUrl: "https://uipath.com",
        description: "Build automation bots for enterprise workflows."
    },
    {
        id: 58,
        title: "Content Writer",
        company: "Byju's",
        location: "Bangalore",
        mode: "Onsite",
        experience: "0-1",
        skills: ["Math", "Science", "Writing"],
        source: "Naukri",
        postedDaysAgo: 3,
        salaryRange: "4–6 LPA",
        applyUrl: "https://byjus.com",
        description: "Create educational content for K-12 students. Subject matter expertise required."
    },
    {
        id: 59,
        title: "SAP Consultant",
        company: "SAP Labs",
        location: "Bangalore",
        mode: "Hybrid",
        experience: "1-3",
        skills: ["ABAP", "SAP HANA"],
        source: "SAP Careers",
        postedDaysAgo: 7,
        salaryRange: "10–14 LPA",
        applyUrl: "https://sap.com",
        description: "Technical consultant for SAP implementation projects."
    },
    {
        id: 60,
        title: "Frontend Developer",
        company: "Zerodha",
        location: "Bangalore",
        mode: "Onsite",
        experience: "1-3",
        skills: ["Vue.js", "JavaScript"],
        source: "Zerodha Tech",
        postedDaysAgo: 2,
        salaryRange: "12–18 LPA",
        applyUrl: "https://zerodha.com",
        description: "Build fast, clean interfaces for trading. Vue.js expertise preferred."
    }
];
